apiVersion: apps/v1
kind: Deployment
metadata:
  name: storagecall
  labels:
    app: storagecall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storagecall
  template:
    metadata:
      labels:
        app: storagecall
    spec:
      containers:
        - name: storagecall
          image: username/taxicall:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5