apiVersion: apps/v1
kind: Deployment
metadata:
  name: storageassign
  labels:
    app: storageassign
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storageassign
  template:
    metadata:
      labels:
        app: storageassign
    spec:
      containers:
        - name: storageassign
          image: username/taxiassign:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5